common/models/UserDetails.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "user_details".
 *
 * @property int $id
 * @property int $user_id
 * @property int $role_id
 * @property string|null $name
 * @property string|null $phone
 * @property string|null $email
 * @property string|null $address
 * @property int|null $gender
 * @property string|null $dob
 * @property string|null $profile_image
 * @property string|null $sign_image
 * @property string $created_at
 * @property string|null $updated_at
 * @property int $is_delete
 */
class UserDetails extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_details';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'role_id'], 'required'],
            [['user_id', 'role_id', 'gender', 'is_delete'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['name', 'phone', 'email', 'address', 'dob', 'profile_image', 'sign_image'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'role_id' => Yii::t('app', 'Role'),
            'name' => Yii::t('app', 'Name'),
            'phone' => Yii::t('app', 'Phone'),
            'email' => Yii::t('app', 'Email'),
            'address' => Yii::t('app', 'Address'),
            'gender' => Yii::t('app', 'Gender'),
            'dob' => Yii::t('app', 'Dob'),
            'profile_image' => Yii::t('app', 'Profile Image'),
            'sign_image' => Yii::t('app', 'Sign Image'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'is_delete' => Yii::t('app', 'Is Delete'),
        ];
    }

    public function getRole()
    {
        return $this->hasOne(Role::className(), ['id' => 'role_id']);
    }

    public function getUserdata()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
}

backend/controllers/UserDetailsController.php
<?php

namespace backend\controllers;

use common\models\Action;
use common\models\Role;
use common\models\User;
use common\models\UserDetails;
use common\models\UserDetailsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;

/**
 * UserDetailsController implements the CRUD actions for UserDetails model.
 */
class UserDetailsController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        if (Yii::$app->user->identity->role_id == 1) {
            return array_merge(
                parent::behaviors(),
                [
                    'verbs' => [
                        'class' => VerbFilter::className(),
                        'actions' => [
                            'delete' => ['POST'],
                        ],
                    ],
                ]
            );
        } else {
            $action_arr = Action::getaccess(Yii::$app->user->identity->role_id ?? 0, Yii::$app->controller->id);
            return [
                'access' => [
                    'class' => AccessControl::class,
                    'rules' => [
                        [
                            'actions' => $action_arr,
                            'allow' => true
                        ],
                        [
                            'actions' => $action_arr,
                            'allow' => true,
                            'roles' => ['@']
                        ]
                    ]
                ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ];
        }
    }

    /**
     * Lists all UserDetails models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new UserDetailsSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single UserDetails model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new UserDetails model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new UserDetails();
        $user = new User();
        $roles = ArrayHelper::map(Role::find()->where(['is_delete' => 0])->andWhere(['!=', 'id', 1])->all(), 'id', 'role_name');

        if ($this->request->isPost) {
            $username = Yii::$app->request->post()['User']['username'];
            $role_id = Yii::$app->request->post()['UserDetails']['role_id'];
            $email = Yii::$app->request->post()['UserDetails']['email'];
            $password = Yii::$app->request->post()['User']['password_hash'];
            $password = Yii::$app->security->generatePasswordHash($password);
            $user->username = $username;
            $user->role_id = $role_id;
            $user->password_hash = $password;
            $user->email = $email;
            if ($user->save()) {
                if ($model->load($this->request->post())) {
                    $max_user = User::find()->max('id');
                    $model->user_id = $max_user;
                    $profile_image = UploadedFile::getInstance($model, 'profile_image');
                    $profile_image_file = $profile_image->baseName . date('Y-m-d') . $profile_image->extension;
                    $pr_image = Yii::getAlias('@storage') . '/profiles/' . $profile_image_file;
                    $profile_image->saveAs($pr_image);
                    $sign_image = UploadedFile::getInstance($model, 'sign_image');
                    $sign_image_file = $sign_image->baseName . date('Y-m-d') . $sign_image->extension;
                    $sn_image = Yii::getAlias('@storage') . '/signatures/' . $sign_image_file;
                    $sign_image->saveAs($sn_image);
                    $model->profile_image = $profile_image_file;
                    $model->sign_image = $sign_image_file;
                    if ($model->save()) {
                        return $this->redirect(['index']);
                    }
                }
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
            'roles' => $roles,
            'user' => $user
        ]);
    }

    /**
     * Updates an existing UserDetails model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $user = new User();
        $roles = ArrayHelper::map(Role::find()->where(['is_delete' => 0])->andWhere(['!=', 'id', 1])->all(), 'id', 'role_name');

        if ($this->request->isPost) {
            if (UploadedFile::getInstance($model, 'profile_image') != '') {
                $profile_image = UploadedFile::getInstance($model, 'profile_image');
                $profile_image_file = $profile_image->baseName . date('Y-m-d') . $profile_image->extension;
                $pr_image = Yii::getAlias('@storage') . '/profiles/' . $profile_image_file;
                $profile_image->saveAs($pr_image);
                $model->profile_image = $profile_image_file;
            }
            if (UploadedFile::getInstance($model, 'sign_image') != '') {
                $sign_image = UploadedFile::getInstance($model, 'sign_image');
                $sign_image_file = $sign_image->baseName . date('Y-m-d') . $sign_image->extension;
                $sn_image = Yii::getAlias('@storage') . '/signatures/' . $sign_image_file;
                $sign_image->saveAs($sn_image);
                $model->sign_image = $sign_image_file;
            } else {
                $model->userdata->username = Yii::$app->request->post()['User']['username'];
                $model->role_id = Yii::$app->request->post()['UserDetails']['role_id'];
                $model->name = Yii::$app->request->post()['UserDetails']['name'];
                $model->phone = Yii::$app->request->post()['UserDetails']['phone'];
                $model->email = Yii::$app->request->post()['UserDetails']['email'];
                $model->address = Yii::$app->request->post()['UserDetails']['address'];
                $model->gender = Yii::$app->request->post()['UserDetails']['gender'];
                $model->dob = Yii::$app->request->post()['UserDetails']['dob'];
                $model->sign_image = $model->sign_image;
                $model->profile_image = $model->profile_image;
            }
            $model->save();
            $model->userdata->save();
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
            'roles' => $roles,
            'user' => $user
        ]);
    }

    /**
     * Deletes an existing UserDetails model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->is_delete = 1;
        $model->save();

        return $this->redirect(['index']);
    }

    public function actionResetprofile($id = '')
    {
        $model = new User();
        if (Yii::$app->request->post()) {
            $reset_password = Yii::$app->request->post()['User']['password_hash'];
            $user = User::find()->where(['id' => $id])->one();
            $user->password_hash = Yii::$app->security->generatePasswordHash($reset_password);
            $user->save();
        }

        return $this->render('resetprofile', [
            'model' => $model,
            'id' => $id
        ]);
    }

    protected function findModel($id)
    {
        if (($model = UserDetails::find()->joinWith(['userdata'])->where(['user_details.id' => $id])->one()) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

frontend/views/user-details/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>

<div class="user-details-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'role_id')->dropDownList($roles, ['prompt' => 'Select', 'required' => true])->label('Role') ?>

    <?= $form->field($model, 'name')->textInput(['required' => true]) ?>

    <?= $form->field($model, 'phone')->textInput(['required' => true, 'type' => 'tel', 'onblur' => 'validate_phone(this.value)']) ?>

    <?= $form->field($model, 'email')->textInput(['required' => true, 'type' => 'email']) ?>

    <?= $form->field($user, 'username')->textInput(['required' => $model->userdata ? false : true, 'value' => $model->userdata ? $model->userdata->username : ''])->label('Username') ?>

    <?= $form->field($user, 'password_hash')->textInput(['type' => 'password', 'minlength' => 8, 'required' => $model->userdata ? false : true, 'hidden' => $model->userdata ? true : false])->label($model->userdata ? '' : 'Password') ?>

    <?= $form->field($model, 'address')->textInput(['required' => true]) ?>

    <?= $form->field($model, 'gender')->dropDownList([1 => 'Male', 2 => 'Female', 3 => 'Other'], ['prompt' => 'Select', 'required' => true]) ?>

    <?= $form->field($model, 'dob')->textInput(['type' => 'date', 'required' => true]) ?><br>

    <?php if ($model->profile_image != '') { ?>
        <?= $form->field($model, 'profile_image')->fileInput(['value' => $model->profile_image, 'accept' => '.png, .jpg, .jpeg']) ?>
    <?php } else { ?>
        <?= $form->field($model, 'profile_image')->fileInput(['required' => true, 'accept' => '.png, .jpg, .jpeg']) ?>
    <?php } ?><br>
    <?php if ($model->sign_image) { ?>
        <?= $form->field($model, 'sign_image')->fileInput(['value' => $model->sign_image, 'accept' => '.png, .jpg, .jpeg']) ?>
    <?php } else { ?>
        <?= $form->field($model, 'sign_image')->fileInput(['required' => true, 'accept' => '.png, .jpg, .jpeg']) ?>
    <?php } ?>

    <?php if ($model->userdata) { ?>
        <a href="<?= Url::toRoute(['user-details/resetprofile', 'id' => $model->user_id]) ?>">Forgot or Edit username/password</a>
    <?php } ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script>
    function validate_phone(phone_no) {
        var pattern = /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/;
        if (!phone_no.match(pattern)) {
            alert('please enter valid phone number')
            event.preventDefault();
        }
    }
</script>

frontend/views/user-details/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var common\models\UserDetailsSearch $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="user-details-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'role_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'gender') ?>

    <?php // echo $form->field($model, 'dob') ?>

    <?php // echo $form->field($model, 'profile_image') ?>

    <?php // echo $form->field($model, 'sign_image') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'is_delete') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/user-details/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var common\models\UserDetails $model */

$this->title = Yii::t('app', 'Create User Details');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'User Details'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-details-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'roles' => $roles,
        'user' => $user
    ]) ?>

</div>

frontend/views/user-details/index.php
<?php

use common\models\UserDetails;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\widgets\Pjax;

/** @var yii\web\View $this */
/** @var common\models\UserDetailsSearch $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = Yii::t('app', 'User Details');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-details-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Create'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); 
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            // 'user_id',
            [
                'attribute' => 'role_id',
                'value' => 'role.role_name'
            ],
            'name',
            'phone',
            'email:email',
            'address',
            [
                'attribute' => 'gender',
                'value' => function ($model) {
                    return $model->gender == 1 ? 'Male' : ($model->gender == 2 ? 'Female' : 'Other');
                }
            ],
            'dob',
            [
                'attribute' => 'profile_image',
                'format' => 'raw',
                'value' => function ($model) {
                    $img = Yii::getAlias('@storageUrl') . '/profiles/' . $model->profile_image;
                    return '<img src="' . $img . '" width="100" height="100">';
                }
            ],
            [
                'attribute' => 'sign_image',
                'format' => 'raw',
                'value' => function ($model) {
                    $img = Yii::getAlias('@storageUrl') . '/signatures/' . $model->sign_image;
                    return '<img src="' . $img . '" width="100" height="100">';
                }
            ],
            //'created_at',
            //'updated_at',
            //'is_delete',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, UserDetails $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                }
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

frontend/views/user-details/resetprofile.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>

<?php $form = ActiveForm::begin([
    'method' => 'POST',
    'action' => ['user-details/resetprofile', 'id' => $id]
]); ?>
<?= $form->field($model, 'password_hash')->textInput(['type' => 'password', 'minlength' => 8, 'required' => true])->label('Reset Password') ?>
<button type="submit" name="reset" value="save" class="btn btn-success">Save</button>
<?php ActiveForm::end(); ?>

frontend/views/user-details/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var common\models\UserDetails $model */

$this->title = Yii::t('app', 'Update User Details: {name}', [
    'name' => $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'User Details'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="user-details-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'roles' => $roles,
        'user' => $user
    ]) ?>

</div>

frontend/views/user-details/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var common\models\UserDetails $model */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'User Details'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="user-details-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user_id',
            'role_id',
            'name',
            'phone',
            'email:email',
            'address',
            'gender',
            'dob',
            'profile_image',
            'sign_image',
            'created_at',
            'updated_at',
            'is_delete',
        ],
    ]) ?>

</div>